#!/usr/bin/env bash
set -u
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
export SCRIPT_ID="43"
. "$ROOT/_shared/logger.sh"
. "$ROOT/_shared/pkg-detect.sh"
. "$ROOT/_shared/file-error.sh"
. "$ROOT/_shared/install-paths.sh"
# Optional: prefer the project fast-download helper (aria2c) when present.
if [ -f "$ROOT/_shared/fast-download.sh" ]; then
  # shellcheck disable=SC1091
  . "$ROOT/_shared/fast-download.sh"
fi

CONFIG="$SCRIPT_DIR/config.json"
[ -f "$CONFIG" ] || { log_file_error "$CONFIG" "config.json missing for 43-install-llama-cpp"; exit 1; }
has_jq || { log_err "[43] jq required to read config"; exit 1; }

TAG=$(jq -r '.install.tag' "$CONFIG")
URL_TPL=$(jq -r '.install.downloadUrlTemplate' "$CONFIG")
ARCH_RAW="$(uname -m)"
ASSET_KEY="$ARCH_RAW"
ASSET=$(jq -r --arg a "$ASSET_KEY" '.install.assets[$a] // empty' "$CONFIG")
if [ -z "$ASSET" ]; then
  log_err "[43] No prebuilt llama.cpp asset mapped for arch '$ARCH_RAW' in $CONFIG"
  exit 2
fi
ASSET="${ASSET//\{tag\}/$TAG}"
DOWNLOAD_URL="${URL_TPL//\{tag\}/$TAG}"
DOWNLOAD_URL="${DOWNLOAD_URL//\{asset\}/$ASSET}"

INSTALL_ROOT_RAW=$(jq -r '.install.installRoot' "$CONFIG")
BIN_DIR_RAW=$(jq -r '.install.binDir' "$CONFIG")
ENV_FILE_RAW=$(jq -r '.install.envFile' "$CONFIG")
INSTALL_ROOT="${INSTALL_ROOT_RAW//\$\{HOME\}/$HOME}"
BIN_DIR="${BIN_DIR_RAW//\$\{HOME\}/$HOME}"
ENV_FILE="${ENV_FILE_RAW//\$\{HOME\}/$HOME}"
PROFILE_MARKER=$(jq -r '.install.profileSnippetMarker' "$CONFIG")
mapfile -t BINARIES < <(jq -r '.install.binaries[]' "$CONFIG")

VERSION_DIR="$INSTALL_ROOT/$TAG"
INSTALLED_MARK="$ROOT/.installed/43.ok"
TMP_DIR="${TMPDIR:-/tmp}/scripts-fixer/llama-cpp"

verify_installed() {
  [ -x "$BIN_DIR/llama-cli" ] || return 1
  "$BIN_DIR/llama-cli" --version >/dev/null 2>&1
}

write_env_file() {
  mkdir -p "$(dirname "$ENV_FILE")" || { log_file_error "$(dirname "$ENV_FILE")" "env-file parent mkdir failed"; return 1; }
  cat > "$ENV_FILE" <<EOF
# Auto-generated by scripts-linux/43-install-llama-cpp -- do not edit by hand.
export LLAMA_CPP_HOME="$VERSION_DIR"
export LLAMA_CPP_BIN="$VERSION_DIR/bin"
export PATH="\$LLAMA_CPP_BIN:\$PATH"
EOF
  log_ok "[43] Wrote env file: $ENV_FILE"
}

ensure_profile_snippet() {
  local rc
  for rc in "$HOME/.bashrc" "$HOME/.zshrc"; do
    [ -f "$rc" ] || continue
    if grep -qF "$PROFILE_MARKER" "$rc" 2>/dev/null; then continue; fi
    {
      printf '\n%s\n' "$PROFILE_MARKER"
      printf '[ -f "%s" ] && . "%s"\n' "$ENV_FILE" "$ENV_FILE"
      printf '%s\n' "# <<< scripts-fixer: llama.cpp <<<"
    } >> "$rc" || { log_file_error "$rc" "could not append llama.cpp env snippet"; continue; }
    log_ok "[43] Sourced env file from: $rc"
  done
}

verb_install() {
  write_install_paths \
    --tool   "llama.cpp (prebuilt binary, $TAG)" \
    --source "$DOWNLOAD_URL" \
    --temp   "$TMP_DIR" \
    --target "$VERSION_DIR/bin (env: $ENV_FILE)"
  log_info "[43] Starting llama.cpp prebuilt-binary installer (tag=$TAG, arch=$ARCH_RAW)"
  if verify_installed; then
    log_ok "[43] Already installed"
    mkdir -p "$ROOT/.installed"; touch "$INSTALLED_MARK"; return 0
  fi
  mkdir -p "$TMP_DIR" "$VERSION_DIR" "$BIN_DIR" || { log_file_error "$TMP_DIR" "tmp/install dir mkdir failed"; return 1; }
  local archive="$TMP_DIR/$ASSET"
  log_info "[43] Downloading $DOWNLOAD_URL"
  local download_ok=1
  if command -v fast_download >/dev/null 2>&1; then
    fast_download "$DOWNLOAD_URL" "$TMP_DIR" || download_ok=0
  elif command -v curl >/dev/null 2>&1; then
    curl -fSL --retry 3 --retry-delay 5 -o "$archive" "$DOWNLOAD_URL" || download_ok=0
  elif command -v wget >/dev/null 2>&1; then
    wget -q -O "$archive" "$DOWNLOAD_URL" || download_ok=0
  else
    log_err "[43] No downloader available (need fast_download/curl/wget)"; return 1
  fi
  if [ "$download_ok" -ne 1 ] || [ ! -s "$archive" ]; then
    log_file_error "$archive" "llama.cpp prebuilt download failed (url=$DOWNLOAD_URL)"; return 1
  fi
  log_info "[43] Extracting $archive -> $VERSION_DIR"
  if ! tar -xzf "$archive" -C "$VERSION_DIR" --strip-components=0; then
    log_file_error "$VERSION_DIR" "tar extract failed (archive=$archive)"; return 1
  fi
  # Some llama.cpp tarballs nest under build/bin; normalise so $VERSION_DIR/bin exists.
  if [ ! -d "$VERSION_DIR/bin" ]; then
    local found
    found="$(find "$VERSION_DIR" -type d -name bin -print -quit 2>/dev/null || true)"
    if [ -n "$found" ] && [ "$found" != "$VERSION_DIR/bin" ]; then
      ln -sfn "$found" "$VERSION_DIR/bin" || log_file_error "$VERSION_DIR/bin" "could not link bin/ from $found"
    fi
  fi
  if [ ! -d "$VERSION_DIR/bin" ]; then
    log_file_error "$VERSION_DIR/bin" "no bin/ directory found inside extracted archive"; return 1
  fi
  log_info "[43] Symlinking binaries into $BIN_DIR"
  for b in "${BINARIES[@]}"; do
    local built="$VERSION_DIR/bin/$b"
    if [ ! -x "$built" ]; then
      log_file_error "$built" "expected binary missing in extracted archive"; continue
    fi
    if ! ln -sf "$built" "$BIN_DIR/$b"; then
      log_file_error "$BIN_DIR/$b" "symlink failed (target=$built)"
    fi
  done
  write_env_file || return 1
  ensure_profile_snippet
  if verify_installed; then
    log_ok "[43] Verify OK (llama-cli --version)"
    log_info "[43] To activate now in this shell:  source \"$ENV_FILE\""
    mkdir -p "$ROOT/.installed"; touch "$INSTALLED_MARK"; return 0
  fi
  log_warn "[43] Verify FAILED after install"; return 1
}
verb_check()  { if verify_installed; then log_ok "[43] Verify OK"; return 0; fi; log_warn "[43] Verify FAILED"; return 1; }
verb_repair() { rm -rf "$VERSION_DIR" "$TMP_DIR"; rm -f "$INSTALLED_MARK"; verb_install; }
verb_uninstall() {
  for b in "${BINARIES[@]}"; do
    rm -f "$BIN_DIR/$b" || log_file_error "$BIN_DIR/$b" "symlink removal failed"
  done
  rm -rf "$INSTALL_ROOT" || log_file_error "$INSTALL_ROOT" "install root removal failed"
  rm -f "$ENV_FILE"
  rm -f "$INSTALLED_MARK"
  log_ok "[43] Removed prebuilt tree, symlinks, and env file (profile snippet left intact -- harmless once env file is gone)"
}
case "${1:-install}" in
  install)   verb_install ;;
  check)     verb_check ;;
  repair)    verb_repair ;;
  uninstall) verb_uninstall ;;
  *) log_err "[43] Unknown verb: $1"; exit 2 ;;
esac
